services:
    # Menus
    admin.menu_level1:
        class: App\Admin\MenuLevel1Admin
        arguments:
            - ~
            - App\Entity\MenuLevel1
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Menu', label: 'sidebarmenu.menu.level1' }
    admin.menu_level2:
        class: App\Admin\MenuLevel2Admin
        arguments:
            - ~
            - App\Entity\MenuLevel2
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Menu', label: 'sidebarmenu.menu.level2' }
    # Pages
    admin.slideshow:
        class: App\Admin\SlideshowAdmin
        arguments:
            - ~
            - App\Entity\Slideshow
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Page', label: 'sidebarmenu.page.slideshow' }
    admin.page:
        class: App\Admin\PageAdmin
        arguments:
            - ~
            - App\Entity\Page
            - App\Controller\Backend\PageAdminController
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Page', label: 'sidebarmenu.page.page' }
    admin.page_image:
        class: App\Admin\PageImageAdmin
        arguments:
            - ~
            - App\Entity\PageImage
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Page', label: 'sidebarmenu.page.page_image', show_in_dashboard: true }
    # Newsletters
    admin.newsletter_group:
        class: App\Admin\NewsletterGroupAdmin
        arguments:
            - ~
            - App\Entity\NewsletterGroup
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Newsletter', label: 'sidebarmenu.newsletter.group' }
    admin.newsletter_user:
        class: App\Admin\NewsletterUserAdmin
        arguments:
            - ~
            - App\Entity\NewsletterUser
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Newsletter', label: 'sidebarmenu.newsletter.user' }
    admin.newsletter:
        class: App\Admin\NewsletterAdmin
        arguments:
            - ~
            - App\Entity\Newsletter
            - App\Controller\Backend\NewsletterAdminController
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Newsletter', label: 'sidebarmenu.newsletter.newsletter' }
    admin.newsletter_post:
        class: App\Admin\NewsletterPostAdmin
        arguments:
            - ~
            - App\Entity\NewsletterPost
            - App\Controller\Backend\NewsletterPostAdminController
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Newsletter', label: 'sidebarmenu.newsletter.newsletter_post', show_in_dashboard: false }
    # Artists
    admin.artist:
        class: App\Admin\ArtistAdmin
        arguments:
            - ~
            - App\Entity\Artist
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Artist', label: 'sidebarmenu.artist.artist' }
    # Archives
    admin.archive:
        class: App\Admin\ArchiveAdmin
        arguments:
            - ~
            - App\Entity\Archive
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Archive', label: 'sidebarmenu.archive.archive' }
    # Settings
    admin.visiting_hours:
        class: App\Admin\VisitingHoursAdmin
        arguments:
            - ~
            - App\Entity\VisitingHours
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Setting', label: 'sidebarmenu.settings.visiting_hours' }
    admin.config_calendar_working_day:
        class: App\Admin\ConfigCalendarWorkingDayAdmin
        arguments:
            - ~
            - App\Entity\ConfigCalendarWorkingDay
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Setting', label: 'sidebarmenu.settings.config_calendar_working_day' }
    admin.user:
        class: App\Admin\UserAdmin
        arguments:
            - ~
            - App\Entity\User
            - ~
            - '@doctrine.orm.entity_manager'
            - '@security.helper'
            - '@twig'
        tags:
            - { name: sonata.admin, manager_type: orm, label_translator_strategy: 'sonata.admin.label.strategy.underscore', group: 'Setting', label: 'sidebarmenu.settings.user' }
