fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            index_name: 'lopati_website_index_app_%kernel.environment%'
            persistence:
                driver:   orm
                model:    App\Entity\Page
                provider: ~
                finder:   ~
#                elastica_to_model_transformer:
#                    query_builder_method: 'getElasticsearchEnabledSortedByNameAndPublishDate'
            properties:
                name:                  { boost: 10 }
                summary:               { boost: 5 }
                description:           { boost: 5 }
                realizationDateString: { boost: 1 }
                place:                 { boost: 1 }
