security:
    enable_authenticator_manager: true
    role_hierarchy:
        ROLE_SONATA_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN_MENU_LEVEL1_ALL
            - ROLE_ADMIN_MENU_LEVEL2_ALL
            - ROLE_ADMIN_PAGE_ALL
            - ROLE_ADMIN_NEWSLETTER_ALL
            - ROLE_ADMIN_NEWSLETTER_GROUP_ALL
            - ROLE_ADMIN_NEWSLETTER_POST_ALL
            - ROLE_ADMIN_NEWSLETTER_USER_ALL
            - ROLE_ADMIN_ARTIST_ALL
            - ROLE_ADMIN_ARCHIVE_ALL
        ROLE_SONATA_SUPER_ADMIN:
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_USER_ALL
        ROLE_ADMIN:
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_SONATA_SUPER_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    encoders:
        App\Entity\User: auto
    providers:
        users:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:     /admin(.*)
            lazy:        true
            entry_point: form_login
            form_login:
                provider:     users
                login_path:   admin_app_login
                check_path:   admin_app_login
                use_forward:  false
                failure_path: null
            logout:
                path:   admin_app_logout
                target: admin_app_login
            guard:
                authenticators:
                    - App\Security\AdminLoginAuthenticator
        main:
            lazy: true
    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/.*, roles: PUBLIC_ACCESS }
