security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER, ROLE_SONATA_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    encoders:
        App\Entity\User: auto
    providers:
        users:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:     /admin(.*)
            lazy:        true
            entry_point: form_login
            form_login:
                provider:     users
                login_path:   admin_app_login
                check_path:   admin_app_login
                use_forward:  false
                failure_path: null
            logout:
                path:   admin_app_logout
                target: admin_app_login
            guard:
                authenticators:
                    - App\Security\AdminLoginAuthenticator
        main:
            lazy: true
    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/, roles: [ ROLE_ADMIN, ROLE_SONATA_ADMIN ] }
        - { path: ^/.*, roles: PUBLIC_ACCESS }
