sonata_admin:
    title:              '%project_title%'
    title_logo:         '/build/logo_lopati_fuchsia.jpg'
    persist_filters:    true
    show_mosaic_button: false
    options:
        skin:                       'skin-black'
        default_icon:               'far fa-folder'
        logo_content:               'icon'
        list_action_button_content: 'icon'
        pager_links:                10
        lock_protection:            true
    templates:
        layout:    'backend/layout.html.twig'
    dashboard:
        groups:
            Menu:
                icon:            '<i class="fas fa-bars"></i>'
                label:           'sidebarmenu.menu.title'
                label_catalogue: 'messages'
#                roles:           [ 'ROLE_ADMIN' ]
                keep_open:       true
            Page:
                icon:            '<i class="fas fa-file"></i>'
                label:           'sidebarmenu.page.title'
                label_catalogue: 'messages'
#                roles:           [ 'ROLE_ADMIN' ]
                keep_open:       true
            Newsletter:
                icon:            '<i class="fas fa-rss"></i>'
                label:           'sidebarmenu.newsletter.title'
                label_catalogue: 'messages'
#                roles:           [ 'ROLE_ADMIN' ]
                keep_open:       true
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: 'col-xs-12'
                settings:
                    content: >
                        <h1 style="margin: -20px 0 10px 0">CMS %project_title%</h1>
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ 'Menu', 'Newsletter' ]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ 'Page' ]
            -
                position: bottom
                type: sonata.block.service.text
                class: 'col-xs-12'
                settings:
                    content: >
                        <div><hr style="margin-top:40px;border-top:solid 1px #d2d6de"><p><i class="fas fa-info-circle"></i> Per rebre assistència tècnica envieu un missatge a <a href="mailto:suport@flux.cat?subject=Ajuda CMS %project_title%" style="color:#000">suport@flux.cat</a></p></div>
