sonata_admin:
    title:              '%project_title%'
    title_logo:         '/build/logo_lopati_fuchsia.jpg'
    persist_filters:    true
    show_mosaic_button: false
    options:
        skin:                       'skin-black'
        default_icon:               'far fa-folder'
        logo_content:               'icon'
        list_action_button_content: 'icon'
        pager_links:                10
        lock_protection:            true
    templates:
        layout:    'backend/layout.html.twig'
    dashboard:
        groups:
            Menu:
                icon:            '<i class="fas fa-bars"></i>'
                label:           'sidebarmenu.menu.title'
                label_catalogue: 'messages'
#                roles:           [ 'ROLE_ADMIN' ]
                keep_open:       true
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
