stof_doctrine_extensions:
    default_locale: '%default_locale%'
    orm:
        default:
            timestampable:  true
            sluggable:      true
            translatable:   true
            softdeleteable: false
            uploadable:     false
            sortable:       false
            blameable:      false
            loggable:       false
            tree:           false
