twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/build': 'styles'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@SonataForm/Form/datepicker.html.twig'
        - 'form/type/edit_newsletter_post_action_button.html.twig'
        - 'form/type/custom_a2lix_translations_field.html.twig'
    globals:
        admin_tag_version: 'v5.07.00'
        developer_name:    '%developer_name%'
        developer_url:     '%developer_url%'
        customer_name:     '%customer_name%'
        customer_email:    '%customer_email%'
        customer_url:      '%customer_url%'
        project_title:     '%project_title%'

when@test:
    twig:
        strict_variables: true
