twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        admin_tag_version: 'v5.02.00'
        developer_name:    '%developer_name%'
        developer_url:     '%developer_url%'
        customer_name:     '%customer_name%'
        customer_url:      '%customer_url%'
        project_title:     '%project_title%'

when@test:
    twig:
        strict_variables: true
