monolog:
    handlers:
        main:
            type:                fingers_crossed
            action_level:        error
            handler:             nested
            buffer_size:         50
            excluded_http_codes: [ 404, 405 ]
        nested:
            path:      '%kernel.logs_dir%/%kernel.environment%.log'
            type:      rotating_file
            level:     debug
            max_files: 15
        console:
            process_psr_3_messages: false
            type:                   console
            channels:               [ '!event', '!doctrine' ]
