imports:
    - { resource: 'services/sonata_admins.yaml' }
    - { resource: 'services/sonata_blocks.yaml' }

parameters:
    default_locale:             '%env(string:DEFAULT_LOCALE)%'
    google_maps_api_key:        '%env(string:GOOGLE_MAPS_API_KEY)%'
    project_title:              '%env(string:PROJECT_TITLE)%'
    developer_name:             '%env(string:DEVELOPER_NAME)%'
    developer_delivery_address: '%env(string:DEV_DELIVERY_ADDRESS)%'
    developer_url:              '%env(string:DEVELOPER_URL)%'
    send_grid_api_key:          '%env(string:SEND_GRID_API_KEY)%'
    customer_name:              '%env(string:CUSTOMER_NAME)%'
    customer_email:             '%env(string:CUSTOMER_EMAIL)%'
    customer_url:               '%env(string:CUSTOMER_URL)%'
    email_address_test_1:       '%env(string:EMAIL_ADDRESS_TEST_1)%'
    email_address_test_2:       '%env(string:EMAIL_ADDRESS_TEST_2)%'
    email_address_test_3:       '%env(string:EMAIL_ADDRESS_TEST_3)%'

services:
    _defaults:
        autowire:      true
        autoconfigure: true
        bind:
            $sendGridApiKey: '%send_grid_api_key%'
            $customerName: '%project_title%'
            $customerEmail: '%customer_email%'
            $emailAddressTest1: '%email_address_test_1%'
            $emailAddressTest2: '%email_address_test_2%'
            $emailAddressTest3: '%email_address_test_3%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    # menus
    app.frontend_main_menu:
        class:   Knp\Menu\MenuItem
        factory: [ '@App\Menu\Frontend\MenuBuilder', createMainMenu ]
        tags:
            - { name: knp_menu.menu, alias: 'frontend_main' }
    app.frontend_language_menu:
        class:   Knp\Menu\MenuItem
        factory: [ '@App\Menu\Frontend\LanguageBuilder', createLanguageMenu ]
        tags:
            - { name: knp_menu.menu, alias: 'frontend_language' }
