---
- hosts: s8
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: execute remote old database export to CSV files
      shell: "mysql --user={{ mysql_db_remote_root_user }} --password={{ mysql_db_remote_root_password }} -A {{ mysql_old_db_remote_name }} < {{ vhost_path_prod }}/current/scripts/database-exports/full-lopati-v1-export-remote-queries.sql"
    - name: move exported CSV files to import directory
      become: true
      shell: "chown root /var/lib/mysql-files/*.csv && chgrp root /var/lib/mysql-files/*.csv && chmod 644 /var/lib/mysql-files/*.csv && mv /var/lib/mysql-files/*.csv {{ vhost_path_prod }}/current/var/csv/imports"
