---
- hosts: s8
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: execute slideshow CSV import command
      shell: "/usr/bin/php7.4 bin/console app:import:slideshow var/csv/imports/slideshow.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute archive CSV import command
      shell: "/usr/bin/php7.4 bin/console app:import:archive var/csv/imports/archive.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute artist CSV import command
      shell: "/usr/bin/php7.4 bin/console app:import:artist var/csv/imports/artist.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute menu level 1 CSV import command
      shell: "/usr/bin/php7.4 bin/console app:import:menu:level1 var/csv/imports/menulevel1.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute menu level 2 CSV import command
      shell: "/usr/bin/php7.4 bin/console app:import:menu:level2 var/csv/imports/menulevel2.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute page CSV import command
      shell: "/usr/bin/php7.4 bin/console app:import:page var/csv/imports/page.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
