---
- hosts: s8
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: execute import slideshow CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:slideshow var/csv/imports/slideshow.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import archive CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:archive var/csv/imports/archive.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import artist CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:artist var/csv/imports/artist.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import artist translations CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:artist:translations var/csv/imports/artist_translations.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import menu level 1 CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:menu:level1 var/csv/imports/menulevel1.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import menu level 1 translations CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:menu:level1:translations var/csv/imports/menulevel1_translations.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import menu level 2 CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:menu:level2 var/csv/imports/menulevel2.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import menu level 2 translations CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:menu:level2:translations var/csv/imports/menulevel2_translations.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import page CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:page var/csv/imports/page.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import page translations CSV import command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:page:translations var/csv/imports/page_translations.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute fetch page menu level 1 CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:fetch:page:menu:level1 var/csv/imports/menulevel1.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute fetch page menu level 2 CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:fetch:page:menu:level2 var/csv/imports/menulevel2.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import newsletter group CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:newsletter:group var/csv/imports/newslettergroup.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import newsletter user CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:newsletter:user var/csv/imports/newsletteruser.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute fetch newsletter group user CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:fetch:newsletter:group:user var/csv/imports/newslettergroupnewsletteruser.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import newsletter CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:newsletter var/csv/imports/newsletter.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import newsletter post CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:newsletter:post var/csv/imports/newsletterpost.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import config calendar working day CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:config:calendar:working:day var/csv/imports/configcalendarworkingday.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import config footer information CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:config:footer:information var/csv/imports/configfooterinformation.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: execute import config footer information translations CSV command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console app:import:config:footer:information:translations var/csv/imports/configfooterinformation_translations.csv --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
    - name: populate Elasticsearch 7 server index command
      shell: "/usr/bin/php{{ vhost_php_version }} bin/console fos:elastica:populate --env=prod"
      args:
        chdir: "{{ vhost_path_prod }}/current/"
