- name: refresh cache
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} cache:clear --no-warmup {{ symfony_cache_options }}"
- name: warm-up cache again
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} cache:warmup {{ symfony_cache_options }}"
- name: install ckeditor
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} ckeditor:install {{ symfony_cache_options }}"
- name: assets install
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} assets:install {{ symfony_cache_options }}"
- name: expose FOS JS routes
  shell: "chdir={{ ansistrano_release_path.stdout }}
    SYMFONY_ENV={{ symfony_env }} {{ symfony_php_path }} {{ symfony_console_path }} fos:js-routing:dump {{ symfony_cache_options }} --format=json --target=public/js/fos_js_routes.json"
- name: compile yarn assets
  shell: "chdir={{ ansistrano_release_path.stdout }}
    yarn install && yarn encore production"
- name: fix symfony cache directory apache ownership
  file:
    path: "{{ ansistrano_release_path.stdout }}/var/cache"
    recurse: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
- name: fix symfony public directory apache ownership
  file:
    path: "{{ ansistrano_release_path.stdout }}/public"
    recurse: yes
    follow: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
